### ISSUE TITLE
CSV encoding problems

### ISSUE THREAD

**Issue by pmarkun** [lianetoolkit/liane-toolkit#162]
I've tried uploading an CSV file with accents and it become gibberish in the system.

I'm using UTF-8.
[CANDIDATOS(AS) - CANDIDATOS(AS) (1).txt](https://github.com/lianetoolkit/liane-toolkit/files/5211437/CANDIDATOS.AS.-.CANDIDATOS.AS.1.txt)

**Comment by miguelpeixe** [comment]
@pmarkun The method for parsing spreadsheet files was not able to identify the encoding for CSV. This fix 2f91eda6c26691a881e1060e4cccfdcec1ed4bf6 should handle csv and txt files correctly.

Its now forcing UTF-8 encoding by using `readAsText` from `FileReader` instead of `readAsArrayBuffer` (preserved for xls, ods and other formats). Not ideal, but should be safe for now.
